version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - ls
      - npm install --unsafe-perm
      - npm run prodTest
      - npm run buildProdBrowser
      - sed 's|rudder-analytics.min.js.map|https://cdn.rudderlabs.com/rudder-analytics.min.js.map|' dist/rudder-analytics.min.js  > dist/prod.js
      - mv dist/prod.js dist/rudder-analytics.min.js
      - aws s3 cp dist/rudder-analytics.min.js s3://$S3_BUCKET_NAME/test.min.js --cache-control max-age=3600 --acl public-read
      - aws s3 cp dist/rudder-analytics.min.js s3://$S3_BUCKET_NAME/v1/test.min.js --cache-control max-age=3600 --acl public-read
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/v1/test.min.js"
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/test.min.js" 
artifacts:
  files:
    - "**/*"